// REGISTER
POST http://localhost:5000/dokter
Content-Type: application/json

{
  "name": "Rakha Muhammad Nauval",
  "email": "rakha@gmail.com",
  "password": "123",
  "confPassword": "123",
  "foto": "nukman.jpg",
  "nohandphone": "08192090",
  "role": "dokter",
  "url":"",
}

###
// lOGIN
POST http://localhost:5000/LoginDokter
Content-Type: application/json

{
  "email": "fadillah@gmail.com",
  "password": "123"
}

###
// MENAMPILKAN DATA user login
GET http://localhost:5000/dokterLogin

###
// MENAMPILKAN SEMUA DATA USER 
GET http://localhost:5000/users 

### 
//LOGOUT
DELETE http://localhost:5000/logout

###
// UPDATE USER
PATCH http://localhost:5000/updateUser/3922bc91-0365-467f-9b74-e3e4abbd4d00
Content-Type: application/json

{
  "name": "Nukman telah diedit",
  "email": "nukman@gmail.com",
  "password": "1234",
  "confPassword": "1234",
  "foto": "nukman.jpg",
  "nohandphone": "08192090",
  "role": "dokter"
}



### 
// REGISTER PASIEN
POST http://localhost:5000/pasien
Content-Type: application/json

{
  "name": "dora emon",
  "alamat":"moh toha bandunng",
  "ttl":"12-10-1998",
  "nohandphone":"089779018328",
  "keluhan":"pantat bisul",
  "dokterSpesialis": "umum"
}


###
// MENAMPILKAN DATA PASIEN 
GET http://localhost:5000/pasienPerawat


###
// MENAMPILKAN DATA PASIEN ID
GET http://localhost:5000/pasienDokter


###
//BUAT JADWAL DOKTER

POST http://localhost:5000/jadwalDokter
Content-Type: application/json

{
  "waktu_pelayanan":"07.00 - 13.00",
  "jadwal_pelayanan":"senin-jumat"
}


###
// BUAT SKEDULE PASIEN 
POST http://localhost:5000/skedulePasien/3